### ISSUE TITLE
when rendering many lib-toastify-toast-container  they will be called as one element even though there's to many of them ? in each component

### ISSUE THREAD

**Issue by elhajoujy** [scenius-software/angular-toastify#52]

**Comment by Lerke** [comment]
Hey @elhajoujy - I haven't tested this, but if you have multiple toast-containers, then I expect you'll get 1 toast per container, since they all listen to the same singleton service which actually provides the toasts. The intended way to use the container is to have just one instance of it at the top level of your application (e.g. in app.component)

**Comment by elhajoujy** [comment]
Yes, you're correct. I only had to set up the container once on the parent, and I've had it working seamlessly since then.

**Comment by Lerke** [comment]
Cool - I assume this can be closed then.
